apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpx-surface-analyzer
  labels:
    app: gpx-surface-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpx-surface-analyzer
  template:
    metadata:
      labels:
        app: gpx-surface-analyzer
    spec:
      containers:
      - name: gpx-surface-analyzer
        image: ghcr.io/kotaicode/gpx_analyzer:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi" 